name: test_workflow
on:
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test job"
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: list files
      run: |
        echo "${{github.repository}} contains files:"
        tree
    
